default:
    -   id: characterNotFound
        message:
            text: "Персонаж не найден, попробуйте выполнить регистрацию снова отправив команду /start"
    -   id: unknownError
        message:
            text: "Ой! Похоже что-то пошло не так. Попробуйте выполнить действие еще раз."
