mainMenu:
    - id: "charBaseInfo"
      text: "${charName} [${accountLevel}]\nКласс: ${charClass} [${charClassLevel}]\nВойска: ${charArmy}"
    - id: "main"
      message:
          action: CREATE
          text: "${charBaseInfo}\n\nВы находитесь в Лагере."
          replyKeyboard:
              replyKeyboardMarkup:
                  resizeKeyboard: true
                  rows:
                      - keyboardRow:
                            - keyboardButton:
                                  text: "Охота на монстров"
                            - keyboardButton:
                                  text: "🚧Арена"
                      - keyboardRow:
                            - keyboardButton:
                                  text: "Персонаж"
                            - keyboardButton:
                                  text: "Армия"
                      - keyboardRow:
                            - keyboardButton:
                                  text: "🚧Привал"
                            - keyboardButton:
                                  text: "🚧Карта"
                      - keyboardRow:
                            - keyboardButton:
                                  text: "🚧Параметры"
    - id: "character"
      message:
          action: CREATE
          text: "${charBaseInfo}"
          replyKeyboard:
              replyKeyboardMarkup:
                  resizeKeyboard: true
                  rows:
                      - keyboardRow:
                            - keyboardButton:
                                  text: "Характеристики"
                            - keyboardButton:
                                  text: "Умения"
                      - keyboardRow:
                            - keyboardButton:
                                  text: "Класс"
                            - keyboardButton:
                                  text: "🚧Экипировка"
                      - keyboardRow:
                            - keyboardButton:
                                  text: "Назад"
    - id: "army"
      message:
          action: CREATE
          text: "${charName} [${accountLevel}]\nВойска: ${charArmy} [${charArmyLevel}]\nТип: ${charArmyType}\nОсобенность: ${charArmyEffect}\nУмения:\n${charArmySkills}\nЗдоровье: ${charArmyHp} x ${charArmyCount}\nАтака: ${charArmyAtk}\nЗащита: ${charArmyDef}\n\nВыберите войска:"
          replyKeyboard:
              inlineKeyboard:
                  dynamicRows:
                      id: armies
                  rows:
                      - inlineKeyboardRow:
                            - inlineKeyboardButton:
                                  text: "Тир 0"
                                  callbackData: "armyList_t0"
                            - inlineKeyboardButton:
                                  text: "Тир 1"
                                  callbackData: "armyList_t1"
                            - inlineKeyboardButton:
                                  text: "Тир 2"
                                  callbackData: "armyList_t2"
                      - inlineKeyboardRow:
                            - inlineKeyboardButton:
                                  text: "Назад"
                                  callbackData: "storyteller_main_menu"
    - id: "charClass"
      message:
          action: CREATE
          text: "${charName} [${accountLevel}]\nКласс: ${charClass} [${charClassLevel}]\n${charClassDescription}\nВыберите класс:"
          replyKeyboard:
              inlineKeyboard:
                  dynamicRows:
                      id: classes
                      maxButtonsPerRow: 1
                  rows:
                      - inlineKeyboardRow:
                            - inlineKeyboardButton:
                                  text: "Назад"
                                  callbackData: "storyteller_main_menu_character"
