main_menu:
    - id: "char_base_info"
      text: "${name} [${account_level}]\nКласс: ${active_class} [${active_class_level}]\nВойска: ${active_army}"
    - id: "main"
      message:
          action: CREATE
          text: "${char_base_info}\n\nВы находитесь в Лагере."
          replyKeyboard:
              replyKeyboardMarkup:
                  resizeKeyboard: true
                  rows:
                      - keyboardRow:
                            - keyboardButton:
                                  text: "Охота на монстров"
                            - keyboardButton:
                                  text: "🚧Арена"
                      - keyboardRow:
                            - keyboardButton:
                                  text: "Персонаж"
                            - keyboardButton:
                                  text: "🚧Армия"
                      - keyboardRow:
                            - keyboardButton:
                                  text: "🚧Привал"
                            - keyboardButton:
                                  text: "🚧Карта"
                      - keyboardRow:
                            - keyboardButton:
                                  text: "🚧Параметры"
    - id: "hero"
      message:
          action: CREATE
          text: "${char_base_info}"
          replyKeyboard:
              replyKeyboardMarkup:
                  resizeKeyboard: true
                  rows:
                      - keyboardRow:
                            - keyboardButton:
                                  text: "🚧Характеристики"
                            - keyboardButton:
                                  text: "Умения"
                      - keyboardRow:
                            - keyboardButton:
                                  text: "🚧Класс"
                            - keyboardButton:
                                  text: "🚧Экипировка"
                      - keyboardRow:
                            - keyboardButton:
                                  text: "Назад"
