spring:
    config:
        import:
            - "classpath:config/localization/dictionary/RU/RU_class.yml"
            - "classpath:config/localization/dictionary/RU/RU_army.yml"
            - "classpath:config/localization/dictionary/RU/RU_skill.yml"
