spring:
    datasource:
        hikari:
            maximumPoolSize: 10
            minimumIdle: 5
            idleTimeout: 30000  # 30 sec
            maxLifeTime: 300000  # 5 min
            keepAliveTime: 30000  # 30 sec
            connectionTimeout: 30000  # 30 sec
        url: jdbc:postgresql://localhost:5432/rtp
        username: storyteller
        password: storyteller
        driver-class-name: org.postgresql.Driver
    liquibase:
        drop-first: false
    jpa:
        show-sql: true

# Feign settings
    cloud.openfeign.client.config:
        default:
            loggerLevel: full
        gateway:
            url: http://localhost:8080
            path: /api/v1/

# Logging settings
debug: true
storyteller:
    action-processor-thread-pool:
        min: 5
        max: 15
        await-termination-timeout: 10s
logging:
    level:
        feign: DEBUG
        root: INFO
        web: DEBUG
        com.github.nnbros.rtp: DEBUG
    file:
        path: 
        name: 