spring:
    datasource:
        url: jdbc:postgresql://93.120.241.248:8543/rtp
        username: storyteller
        password: q8YG5lxNz6bRGPH9iBFK
        driver-class-name: org.postgresql.Driver
    liquibase:
        drop-first: false
    jpa:
        show-sql: true

# Feign settings
    cloud.openfeign.client.config:
        default:
            loggerLevel: full
        gateway:
            url: "http://192.168.0.106:8080"
            path: "/api/v1/"

# Logging settings
debug: true
storyteller:
    action-processor-thread-pool:
        min: 5
        max: 15
        await-termination-timeout: 10s
logging:
    level:
        feign: DEBUG
        root: INFO
        web: DEBUG
        com.github.nnbros.rtp: DEBUG
    file:
        path: 
        name: 