localization.classes:
    rogue:
        name: "Плут"
        description: "Мастер подлых трюков"

    warrior:
        name: "Воин"
        description: "Сильный боец ближнего боя, эффективен против копейщиков"
