ui:
    registration_messages:
        registration_request: "Готовы ли Вы начать путешествие или хотите что-то изменить?"
        success: "Поздравлем, вы успешно зарегистрировались!"
        character:
            not_found: "Персонаж не найден, попробуйте выполнить регистрацию снова отправив команду /start"
            gender:
                request: "Выберите пол вашего персонажа"
                summary: "Пол персонажа: %s"
                male: "Мужской"
                female: "Женский"
            name_request: "Введите имя персонажа.\nТребования к нику: от 4 до 16 символов, без пробелов, состоит из латинских, кирилических символов и цифр.
             Является уникальным, не содержит оскорбления, не имитирует административный аккаунт, не нарушает законы РФ."
            non_valid_name: "Введенное имя не соответствует требованиям."
            name_summary: "Имя персонажа: %s"
            class_request: "Выберите стартовый класс. В дальнейшем вы сможете открыть любое количество новых классов."
            class_short_description_template: "%s: %s\n"
            class_full_description_template: "Стартовые умения:\n%s"
            class_summary: "Выбранный класс: %s"